# main.yml
name: publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add safe workspace
        run: /
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@master
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: use Node.js 12.16.2
        uses: actions/setup-node@master
        with:
          node-version: 12.16.2
      - name: npm install & build
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
